import {useEffect,useRef,useState} from 'react';
import {Details,Result} from '../lib/types';
import {renderAd} from '../lib/render-ad';
import {validate} from '../lib/validation';
export default function ResultEditor({result,onChange,back}:{result:Result;onChange:(r:Result)=>void;back:()=>void}){
 const canvas=useRef<HTMLCanvasElement>(null),[error,setError]=useState(''),[ready,setReady]=useState<Result|null>(null),[downloading,setDownloading]=useState(false);
 const errors=validate(result.details);
 useEffect(()=>{let active=true;setReady(null);setError('');
  if(Object.keys(validate(result.details)).length)return;
  const draft=document.createElement('canvas');
  renderAd(draft,result).then(()=>{if(!active)return;const visible=canvas.current!;visible.width=draft.width;visible.height=draft.height;visible.getContext('2d')!.drawImage(draft,0,0);setReady(result);}).catch(e=>{if(active)setError(e.message)});
  return()=>{active=false};
 },[result]);
 function updateDetails(details:Details){const discount=details.old_price?Math.round((Number(details.old_price)-Number(details.current_price))/Number(details.old_price)*100):null;onChange({...result,details,discount_percent:discount})}
 const field=(key:'product_name'|'current_price'|'old_price'|'address',label:string)=><label>{label}<input value={result.details[key]||''} inputMode={key.includes('price')?'decimal':undefined} maxLength={key==='product_name'?100:160} onChange={e=>updateDetails({...result.details,[key]:key==='old_price'?(e.target.value||null):e.target.value})} aria-invalid={!!errors[key]}/>{errors[key]&&<span className="field-error">{errors[key]}</span>}</label>;
 async function download(){if(ready!==result||error||Object.keys(errors).length)return;setDownloading(true);try{const blob=await new Promise<Blob>((resolve,reject)=>canvas.current!.toBlob(b=>b?resolve(b):reject(new Error('Could not download your ad. Please try again.')),'image/png'));const url=URL.createObjectURL(blob);const link=document.createElement('a');link.href=url;link.download='postready-ad.png';link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}catch(e){setError(e instanceof Error?e.message:'Could not download your ad. Please try again.')}finally{setDownloading(false)}}
 return <section className="panel result"><span className="eyebrow">YOUR ADVERTISEMENT</span><h1>Make it yours.</h1><p>Edit the words below, then download your advertisement.</p><canvas ref={canvas} aria-label="Generated advertisement preview"/>{error&&<p className="error" role="alert">{error}</p>}{Object.keys(errors).length>0&&<p className="error" role="alert">Correct the details below to update your preview and download.</p>}
 <fieldset><legend>Words inside your advertisement</legend><p className="contact-help">These edits change your image. The product artwork stays the same.</p><div className="form-grid"><label>Headline<input value={result.image_text.headline} maxLength={100} onChange={e=>onChange({...result,image_text:{...result.image_text,headline:e.target.value}})}/></label><label>Ad description<textarea value={result.image_text.tagline} maxLength={180} rows={3} onChange={e=>onChange({...result,image_text:{...result.image_text,tagline:e.target.value}})}/></label>{field('current_price','Current price · ETB')}{field('old_price','Old price · ETB (optional)')}{field('address','Shop address (optional)')}</div><div className="contacts-group"><strong>Contacts shown in the ad</strong>{result.details.contacts.map((contact,index)=><div className="contact" key={index}><select aria-label={`Ad contact type ${index+1}`} value={contact.kind} onChange={e=>updateDetails({...result.details,contacts:result.details.contacts.map((c,i)=>i===index?{...c,kind:e.target.value}:c)})}>{['Phone','Telegram','TikTok','Instagram','Other'].map(s=><option key={s}>{s}</option>)}</select><input aria-label={`Ad contact value ${index+1}`} value={contact.value} maxLength={120} onChange={e=>updateDetails({...result.details,contacts:result.details.contacts.map((c,i)=>i===index?{...c,value:e.target.value}:c)})}/></div>)}{errors.contact&&<span className="field-error">{errors.contact}</span>}</div></fieldset>
 <div className="copy-preview"><label>Social post caption<textarea rows={5} maxLength={1500} value={result.social_caption} onChange={e=>onChange({...result,social_caption:e.target.value})}/></label><p className="contact-help">Separate from your image. You can select and copy this text for your post.</p></div><div className="actions"><button className="secondary" onClick={back}>← Back to details</button><button className="primary" disabled={ready!==result||!!error||Object.keys(errors).length>0||downloading} onClick={download}>{downloading?'Preparing download…':'Download PNG ↓'}</button></div></section>
}
